apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elastic
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.port: 5601

    server.ssl.enabled: true
    server.ssl.certificate: /etc/ssl/tls.crt
    server.ssl.key: /etc/ssl/tls.key


    elasticsearch.hosts: ["https://es-topology.elastic.svc:9200"]
    elasticsearch.username: kibanaro
    elasticsearch.password: P(IIVQhAWxXvsg6V
    elasticsearch.ssl.certificateAuthorities: /etc/ssl/tls.crt
    # xpack.security.enabled: false 

    # logging.silent: false
    # logging.quiet: false

# get elasticsearch.username - kubectl get secret -n elastic es-topology-elastic-cred -o jsonpath='{.data.username}' | base64 -d

# get elasticsearch.password - kubectl get secret -n elastic es-topology-elastic-cred -o jsonpath='{.data.password}' | base64 -d